Repository quant-aq/r-quantaq, pull requests merged in 2023-08, with the labels that each got.

#1 Initial functional package
  .gitignore
  DESCRIPTION
  LICENSE
  LICENSE.md
  NAMESPACE
  QuantAQAPIClient.Rproj
  R/api_calls.R
  R/setup.R
  R/wrappers.R
  README.md
  man/access_client.Rd
  man/as.data.frame.account.Rd
  man/as.data.frame.calibration_models.Rd
  man/as.data.frame.device_data.Rd
  man/as.data.frame.devices.Rd
  man/as.data.frame.teams.Rd
  man/authenticate_client.Rd
  man/build_api_url.Rd
  man/format_params.Rd
  man/get_data.Rd
  man/get_data_by_date.Rd
  man/get_device_metadata.Rd
  man/get_devices.Rd
  man/get_logs.Rd
  man/get_models.Rd
  man/get_teams.Rd
  man/paginate.Rd
  man/request.Rd
  man/requests.Rd
  man/setup_client.Rd
  man/unnest_all.Rd
  man/whoami.Rd
  tests/testthat.R
  tests/testthat/setup.R
  tests/testthat/test-api_calls.R
  tests/testthat/test-wrappers.R
Labels: enhancement

#2 Minor updates to README.md
  README.md
Labels: docs

#3 Added docs and patched an error in the raw data-by-date call
  .github/release-drafter.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/release-drafter.yml
  .github/workflows/run-tests.yml
  DESCRIPTION
  R/wrappers.R
  README.md
Labels: bug, docs
